version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "10000:10000"
    env_file:
      - .env
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
